name: Windows Build and Release
on:
  push: # Run on every push
    branches:
      - main
      - develop
      - 'feature/*' # Optional: Runs on feature branches
    tags:
      - 'v*' # Triggers release only on version tags
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc # Or x86_64-pc-windows-gnu if needed
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: target/release/*.exe
          retention-days: 7 # Keep artifacts for 7 days
  release:
    name: Create GitHub Release
    needs: build # Ensure build completes first
    if: startsWith(github.ref, 'refs/tags/') # Only run on tags
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Binary
        uses: actions/download-artifact@v4
        with:
          name: windows-binary
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
          generate_release_notes: true
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
